name: Build and push main container image
on:
  push:
    branches:
      - main
      - fix/diloco-amd-image
permissions:
  contents: read
  packages: write
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
jobs:
  build-main:
    runs-on: exalsius-runner-default
    strategy:
      matrix:
        include:
          - image_tag: cuda
            dockerfile: Dockerfile.cuda

          - image_tag: rocm
            dockerfile: Dockerfile.rocm
    steps:
      - name: Free up disk space
        run: |
          echo "Cleaning up disk space"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo apt-get clean
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Dev Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          load: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}-${{ github.sha }}
          # --- caching (per-image cache ref) ---
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}:buildcache,mode=max
